"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestIngSoftModel,
	#superclass : #PackageManifest,
	#category : #'IngSoft2-Model-Manifest'
}

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleGRUndeclaredVariableRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'IngSoft2-Model')) #'2020-08-04T05:06:35.902407-03:00') )
]

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleRBCollectionMessagesToExternalObjectRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'IngSoft2-Model')) #'2020-08-04T03:56:47.34983-03:00') )
]

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleRBExcessiveArgumentsRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'IngSoft2-Model')) #'2020-08-04T06:26:15.82322-03:00') )
]

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleRBImplementedNotSentRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'IngSoft2-Model')) #'2020-08-04T05:46:54.343499-03:00') )
]

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleRBReturnsIfTrueRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'IngSoft2-Model')) #'2020-08-04T04:11:06.200851-03:00') )
]

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleRBSelfSentNotImplementedRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'IngSoft2-Model')) #'2020-08-04T05:06:51.511013-03:00') )
]

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleRBSentNotImplementedRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'IngSoft2-Model')) #'2020-08-04T06:04:11.456943-03:00') )
]

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleRBTempVarOverridesInstVarRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'IngSoft2-Model')) #'2020-08-04T03:48:15.077323-03:00') )
]

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'IngSoft2-Model')) #'2020-08-04T05:47:02.312724-03:00') )
]
